language: objective-c

before_install:
  - wget "https://raw.githubusercontent.com/enckse/travis-mono-scripts/master/download-all.sh"
  - sudo chmod a+x download-all.sh
  - ./download-all.sh

script: make analyze stylecop=/opt/stylecop/StyleCopCmd.Console.exe nunit=./nunit-wrapper
